# Generated by Django 5.2.6 on 2025-09-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('assignedTo', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], default='P3', max_length=5)),
                ('assignedDate', models.DateTimeField()),
                ('dueDate', models.DateTimeField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Complete', 'Complete'), ('Expired', 'Expired')], default='Active', max_length=20)),
            ],
        ),
    ]
