# Generated by Django 5.2.6 on 2025-09-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('assignedTo', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=5)),
                ('assignedDate', models.DateTimeField()),
                ('dueDate', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
